### ISSUE TITLE
Fix Self Closing Tags

### ISSUE THREAD

**Issue by brankosekulic** [goschevski/tagster#2]
```
var image = new Tagster('img', { src: '/default.png' }).element;
```

Output should be 

```
<img src="/default.png" />
```

instead of

```
<img src="/default.png"></img> 
```

**Comment by goschevski** [comment]
Hi Brane,

I added image helper for now, but this should be fixed by passing options as object, so we can have flag for elements without closing tag, for example: `closing: true`.

Other solution is to create list of elements without closing tag, and to recognise those ones and atomically remove closing tag.

**Comment by brankosekulic** [comment]
Thanks, there is third option as well:

http://haml.info/docs/yardoc/file.REFERENCE.html#empty_void_tags_

**Comment by goschevski** [comment]
It should work now using backslash in the end of element name:

```
var image = new Tagster('img/', { src: 'img/partizan.png', alt: 'Volim Partizan!' }).element;
image.should.equal('<img src="img/partizan.png" alt="Volim Partizan!">');
```
